title: "yriica notes"
description: "modern blog with Jekyll + Tailwind"
baseurl: ""
remote_theme: null
plugins:
  - jekyll-remote-theme
markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:day/:title/
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - assets/css/input.css
