title: "yriica notes"
description: "lifelog & digital playground"
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:day/:title/
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - assets/css/input.css
